### ISSUE TITLE
When a round is restarted...

### ISSUE THREAD

**Issue by Tamago4a** [ServerMod/MultiAdmin#239]
Installed multiadmin. I made the following configuration:
```yaml
config_location:
appdata_location: C:\Users\PC\AppData\Roaming\SCP Secret Laboratory
disable_config_validation: False
share_non_configs: True
multiadmin_log_location: logs
multiadmin_nolog: False
multiadmin_debug_log: True
multiadmin_debug_log_blacklist:
multiadmin_debug_log_whitelist:
use_new_input_system: True
port: 7777
copy_from_folder_on_reload:
folder_copy_whitelist:
folder_copy_blacklist:
folder_copy_round_queue:
folder_copy_round_queue_whitelist:
folder_copy_round_queue_blacklist:
randomize_folder_copy_round_queue: False
manual_start: false
max_memory: 2048
restart_low_memory:
restart_low_memory_roundend:
random_input_colors: False
restart_every_num_rounds: -1
restart_every_num_rounds_counting: True
safe_server_shutdown: True
safe_shutdown_check_delay: 150
safe_shutdown_timeout: 10000
server_restart_timeout: 10
server_stop_timeout: 10
server_start_retry: True
server_start_retry_delay: 10000
servers_folder: servers
set_title_bar: True
start_config_on_full:
```
At the moment of the round restart, the "config_gameplay.txt" file is opened every time. What have I done wrong?
![Безымянный](https://user-images.githubusercontent.com/47304666/94997234-7a5a7c00-05b2-11eb-9233-0722cecdda2b.png)

**Comment by Dankrushen** [comment]
That is set by `config_location`

**Comment by Tamago4a** [comment]
> That is set by `config_location`

The configuration description in your github is very strangely styled. I do not understand what I need to specify in this parameter.

**Comment by Tamago4a** [comment]
You said some nonsense. I found the reason. The reason is in one blank line.
As I understood it:
1. I removed all "empty" lines.
![Снимок](https://user-images.githubusercontent.com/47304666/95004068-0f7b6600-05ef-11eb-98f6-6a9167d9f2a8.PNG)
2. Checked this bug. He has gone.
3. I started to add blank lines from this list one by one:
```yaml
folder_copy_round_queue:
copy_from_folder_on_reload:
config_location:
appdata_location:
multiadmin_debug_log_blacklist:
multiadmin_debug_log_whitelist:
folder_copy_whitelist:
folder_copy_blacklist:
folder_copy_round_queue_whitelist:
folder_copy_round_queue_blacklist:
restart_low_memory:
restart_low_memory_roundend:
start_config_on_full:
```
4. As a result, I realized that the error in
```yaml
folder_copy_round_queue:
```
If this line is in the config then some kind of nonsense happens.
If you don't believe you can check it yourself. I am showing you a real bug.
